name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel twine

    - name: Bump version
      run: |
        VERSION=$(python3 setup.py --version)
        echo "Current version: $VERSION"
        NEW_VERSION=$(python3 -c "v='$VERSION'.split('.'); v[-1]=str(int(v[-1])+1); print('.'.join(v))")
        echo "New version: $NEW_VERSION"
        sed -i "s/version='$VERSION'/version='$NEW_VERSION'/" setup.py
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "Bump version to $NEW_VERSION"
        git push

    - name: Build package
      run: |
        rm -rf dist/
        python3 setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
